### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by blois** [Quansight-Labs/jupyter-output-spec#2]
A couple of comments based on a quick first-pass.

For background, I was exploring a similar API a while back in https://github.com/blois/jupyterlab-comms/blob/master/src/jupyterComms.ts, I am in favor of this general approach.

- Can the NPM/jsdelivr dependencies be generalized to just ES6 module URLs?
- Would prefer to use AsyncIterables over Observables, since they are ES-native and just syntactic sugar over promises & generators.
 - Is there a clear need for registerCommTarget? It seems like the vast majority of scenarios the client would connect back to the kernel.
 - Is the `data: Observable<T>` an implicit comm channel? How does this work? If this is a comm channel, is createComm needed?
 - How does notebook persistence work? In widgets it's basically inferred from the series of Comms messages. The data being sent probably needs to be more structured, since arrays cannot be sent.
 - The observable data/nodes/kernel seems complex. Will data be arriving in any order on each of those? So you get data, then some time later, get an array of nodes to render into, then sometime later get a kernel? Seems like initial render should always have Data and a Node.
 - Exposing the kernel connection state to all renderers seems a bit leaky. Disconnects/reconnects will be frequent, but may have no impact on the current state of the renderer. It seems like this could be encapsulated in the createComm API- when a disconnect happens then the stream of data finishes.

```typescript
type Comm = {
    send(data: object): Promise<void>;
    close();
    // Iterator will end when closed.
    msgs: AsyncIterator<object>;
}

/**
 * Renders the `data` to the `nodes` using the `kernel`.
 * 
 * Returns a promise that resolves after finishing rendering initial data.
 */
type RenderFn<T extends object> = (options: {
    // the actual mime data
    data: T,
    // the node we want to render on
    node: Element,
    // Will reject if not connected and cannot connect.
    createComm(targetName: string): Promise<Comm>
}) => Promise<void>
```

**Comment by saulshanabrook** [comment]
Hey @blois Thank you so much for all your comments! I wasn't watching this repo so just seeing this now.

All really good points. I opened https://github.com/Quansight-Labs/jupyter-output-spec/pull/3 to address a number of these: https://github.com/Quansight-Labs/jupyter-output-spec/pull/3

> Can the NPM/jsdelivr dependencies be generalized to just ES6 module URLs?

I like this idea! I think it might still be nice to include the package name as well, optionally, so in JupyterLab, we could have a build that includes the renderer, and it could use this instead of reaching out to some external CDN.

> Would prefer to use AsyncIterables over Observables, since they are ES-native and just syntactic sugar over promises & generators.

Sounds good to me. 

> Is there a clear need for registerCommTarget? It seems like the vast majority of scenarios the client would connect back to the kernel.

Yep good point! removing this.

> Is the data: Observable<T> an implicit comm channel? How does this work? If this is a comm channel, is createComm needed?

No it's for updating displays: https://mindtrove.info/jupyter-tidbit-display-handles/

I use this sometimes to get data from the kernel to an renderer, without having to use comms, where the renderer can still preserve it's state but just update with respect to the new data. 

 > How does notebook persistence work? In widgets it's basically inferred from the series of Comms messages. The data being sent probably needs to be more structured, since arrays cannot be sent.

Great question... Another related thing is the ability to save other mimetypes after rendering. We use this in the vega rendering, so after it finishes  for the first time, it saves a PNG so it can be rendered in other clients. 

> The observable data/nodes/kernel seems complex. Will data be arriving in any order on each of those? So you get data, then some time later, get an array of nodes to render into, then sometime later get a kernel? Seems like initial render should always have Data and a Node.

Yes the idea is that you might have any number of them at any time, but you are right, we should scope it more closely. I changed it

> Exposing the kernel connection state to all renderers seems a bit leaky. Disconnects/reconnects will be frequent, but may have no impact on the current state of the renderer. It seems like this could be encapsulated in the createComm API- when a disconnect happens then the stream of data finishes.


connects/disconnects, shouldn't be broadcasted, you are right. But what about kernel changes? Or restarts? But I see what you are saying. Basically, if a kernel ends, disconnect all it's comms, and the renderer will know that it happened and can reconnect if it likes.

Only question is, should the renderer be able to tell the difference between a kernel being changed/restating and the kernel intentionally closing the comm?

**Comment by saulshanabrook** [comment]
> How does notebook persistence work? In widgets it's basically inferred from the series of Comms messages. The data being sent probably needs to be more structured, since arrays cannot be sent.

I think maybe this should be handled by on the kernel side, by updating the data. For example, I could see the flow going like this:

1. You run something in a kernel that creates one of these outputs
2. That output is rendered
3. User interacts with it, and we want to preserve that interaction in the notebook somehow
4. Frontend opens comm connection to kernel with update state of widget
5. kernel calls update display, to set new data in package, this is now saved in the notebook output
6. frontend gets new data update, it ignores since this is already the state it's in.

**Comment by saulshanabrook** [comment]
> connects/disconnects, shouldn't be broadcasted, you are right. But what about kernel changes? Or restarts? But I see what you are saying. Basically, if a kernel ends, disconnect all it's comms, and the renderer will know that it happened and can reconnect if it likes.

I think you are right, it's better if its simpler. I removed the kernel interface: https://github.com/Quansight-Labs/jupyter-output-spec/pull/4

**Comment by blois** [comment]
> in JupyterLab, we could have a build that includes the renderer, and it could use this instead of reaching out to some external CDN.

Plotly for example controls this via [configuration](https://plotly.com/python/renderers/#interactive-renderers) in Python. I'm a bit wary of fallbacks as it seems more like another potential point of failure. JupyterLab could implement an option which rejected any URLs which did not originate from the notebook server.

**Comment by saulshanabrook** [comment]
> JupyterLab could implement an option which rejected any URLs which did not originate from the notebook server.

I guess we could have a way of saying "hey we already built this URL into our bundle, use that instead of fetching that URL".

> JupyterLab could implement an option which rejected any URLs which did not originate from the notebook server.

We wouldn't wanna load a local file, we would wanna say that it's already been bundled in our large webpack bundle and so it's already loaded.

But I see your point.  https://github.com/Quansight-Labs/jupyter-output-spec/pull/5

**Comment by blois** [comment]
Really think this is looking good! Opened separate issues for additional thoughts.

**Comment by saulshanabrook** [comment]
> Really think this is looking good! Opened separate issues for additional thoughts.

Great! I just added you as a maintainer here as well.
